export const SIGNUP_START = "SIGNUP_START"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const LOGIN_START= "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const SIGNOUT_SUCCESS="SIGNOUT_SUCCESS"

export const RESET_PASSWORD="RESET_PASSWORD"

export const VALID_RESETCODE="VALID_RESETCODE"

export const INVALID_RESETCODE="INVALID_RESETCODE"

export const PASSWORD_CHANGED_START="PASSWORD_CHAANGE_START"
export const PASSWORD_CHANGED_SUCCESS="PASSWORD_CHANGED_SUCCESS"
export const PASSWORD_CHANGED_FAIL="PASSWORD_CHANGED_FAIL"

//products

export const ADD_PRODUCT_START = "ADD_PRODUCT_START"
export const ADD_PRODUCT_SUCCESS = "ADD_PRODUCT_SUCCESS"
export const ADD_PRODUCT_FAIL = "ADD_PRODUCT_FAIL"