export const SIGNUP_START = "SIGNUP_START"
export const SIGNUP_SUCCESS = "SIGNUP_SUCCESS"
export const SIGNUP_FAIL = "SIGNUP_FAIL"

export const LOGIN_START= "LOGIN_START"
export const LOGIN_SUCCESS = "LOGIN_SUCCESS"
export const LOGIN_FAIL = "LOGIN_FAIL"

export const SIGNOUT_SUCCESS="SIGNOUT_SUCCESS"

export const RESET_PASSWORD="RESET_PASSWORD"

export const VALID_RESETCODE="VALID_RESETCODE"

export const INVALID_RESETCODE="INVALID_RESETCODE"

export const PASSWORD_CHANGED_START="PASSWORD_CHAANGE_START"
export const PASSWORD_CHANGED_SUCCESS="PASSWORD_CHANGED_SUCCESS"
export const PASSWORD_CHANGED_FAIL="PASSWORD_CHANGED_FAIL"

//products

export const CREATE_PRODUCT_START = "CREATE_PRODUCT_START"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAIL = "CREATE_PRODUCT_FAIL"

// carts
export const INCREMENT = "INCREMENT"
export const DECREMENT = "DECREMENT"
export const ADD_TO_CART = "ADD_TO_CART"
export const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export const ADJUST_QTY = "ADJUST_QTY"

//order
export const PURCHASE_PRODUCT_START = "PURCHASE_PRODUCT_START"
export const PURCHASE_PRODUCT_SUCCESS = "PURCHASE_PRODUCT_SUCCESS"
export const PURCHASE_PRODUCT_FAIL = "PURCHASE_PRODUCT_FAIL"